### ISSUE TITLE
Several push events sent after spacecraft has been deleted

### ISSUE THREAD

**Issue by rtubio** [satnet-project/server#34]
Several event notifications are sent through pusher.com after the spacecraft has been deleted.

**Comment by rtp-calpoly** [comment]
This is not a bug, as first thought. Every time a spacecraft is deleted, its associated pass slots are removed individually, one by one. Therefore, each of them generates a signal to update the list of pass slots at remote clients. This process blocks the execution of the spacecraft deletion, which turns out to provoke a delay in the latter.

Therefore, this notification task has to be executed as an isolated thread or task, being Celery (integrated with Django) the more out-of-the-box option. Celery runs tasks as separate threads, which is a good option for all this.

Another improvement will be to "pack" together all the notifications of the erased pass slots and send a single event back to the remote clients.

**Comment by rtubio** [comment]
For the second release, the pusher notifications can be enabled/disabled, so that they can be used to demonstrate potential technologies and collaboration capacities and they won't jeopardize the operation of the system.
